version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SPREADSHEET_URL=${SPREADSHEET_URL}
    volumes:
      - ./data:/app/data  # Optional: persist database
    restart: unless-stopped